title = "Mark Chmarny"
author = "Mark Chmarny"
copyright = "2021-{{ YEAR }}"
description = "few longer thoughts, <br/>because every once in a while <br/>140 characters is just not enough"
profilePicture = "images/profile.png"
keywords = ""
displayMode = "dark"
contentratio = 0.7
readMore = false
favicon = "favicons/"
customCss = ["css/custom.css"]
mainSections = ["posts"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = true
googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]
singleDateFormat = "2006-01-02"
indexDateFormat = "2006-01-02"
listDateFormat = "2006-01-02"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

## Math settings
[math]
enable = false
use = "katex"

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.

[[socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/mchmarny"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/mchmarny"

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:blog@chmarny.com"

